import OneChannelCNNUniversality.SharedBiasGeometry
import OneChannelCNNUniversality.SharedBiasOneLayerObstruction

/-!
# Sharp depth for initializing an input-independent spatial carrier

A single shared-bias convolution/ReLU layer sends the zero input to a
spatially constant image.  Hence, on every input domain containing zero, a
one-layer output which is independent of the input must be spatially
constant.

Two layers suffice.  The first uses the zero kernel and bias `1`, erasing the
input and producing a constant rectangle.  The second uses horizontal
boundary differencing; zero extension then turns that rectangle into the
exact left-edge indicator.  The resulting nonuniform carrier is independent
of every input.  Together these statements give a sharp positive-depth bound
of two layers.
-/

namespace OneChannelCNNUniversality

/-- An image is spatially nonuniform when two of its sites have different
values. -/
def SpatiallyNonuniform {rows cols : ℕ} (carrier : Image rows cols) : Prop :=
  ∃ p₁ q₁ p₂ q₂, carrier p₁ q₁ ≠ carrier p₂ q₂

/-- Every one-layer shared-bias map sends the zero image to the constant
image whose value is the ReLU of its scalar bias. -/
theorem sharedLayerEval_zero {kRows kCols rows cols : ℕ}
    (w : Kernel kRows kCols) (b : ℝ) :
    sharedLayerEval w b (0 : Image rows cols) =
      constantImage (rows + kRows - 1) (cols + kCols - 1) (relu b) := by
  funext p q
  simp [sharedLayerEval, layerEval, constantImage, fullConv]

/-- On a domain containing zero, every input-independent output of one
shared-bias layer equals the spatially constant image `relu b`. -/
theorem oneLayer_constant_on_zero_mem_eq_relu_bias
    {kRows kCols rows cols : ℕ}
    (K : Set (Image rows cols)) (hzero : (0 : Image rows cols) ∈ K)
    (w : Kernel kRows kCols) (b : ℝ)
    (carrier : Image (rows + kRows - 1) (cols + kCols - 1))
    (hconstant : ∀ x ∈ K, sharedLayerEval w b x = carrier) :
    carrier = constantImage (rows + kRows - 1) (cols + kCols - 1) (relu b) := by
  rw [← hconstant 0 hzero]
  exact sharedLayerEval_zero w b

/-- Thus one shared-bias layer cannot initialize a spatially nonuniform
carrier independently of the input on any domain containing zero. -/
theorem not_oneLayer_nonuniform_inputIndependent_on_zero_mem
    {kRows kCols rows cols : ℕ}
    (K : Set (Image rows cols)) (hzero : (0 : Image rows cols) ∈ K)
    (w : Kernel kRows kCols) (b : ℝ) :
    ¬ ∃ carrier : Image (rows + kRows - 1) (cols + kCols - 1),
      SpatiallyNonuniform carrier ∧
        ∀ x ∈ K, sharedLayerEval w b x = carrier := by
  rintro ⟨carrier, ⟨p₁, q₁, p₂, q₂, hne⟩, hconstant⟩
  have hcarrier := oneLayer_constant_on_zero_mem_eq_relu_bias
    K hzero w b carrier hconstant
  apply hne
  rw [hcarrier]
  rfl

/-- The explicit two-layer network: erase the input to the constant image
`1`, then use the zero-extension boundary to extract its positive left edge. -/
def twoLayerLeftBoundaryCarrierNetwork (rows cols : ℕ) :
    SharedBiasNetworkTo 2 2 rows cols
      ((rows + 2 - 1) + 2 - 1) ((cols + 2 - 1) + 2 - 1) :=
  SharedBiasNetworkTo.cons (0 : Kernel 2 2) 1
    (SharedBiasNetworkTo.single horizontalBoundaryKernel 0)

/-- The constructed carrier network has exactly two convolution/ReLU
layers. -/
@[simp] theorem twoLayerLeftBoundaryCarrierNetwork_depth (rows cols : ℕ) :
    (twoLayerLeftBoundaryCarrierNetwork rows cols).net.depth = 2 := by
  rfl

/-- The two-layer network evaluates to the exact left-boundary indicator on
every input. -/
theorem twoLayerLeftBoundaryCarrierNetwork_eval {rows cols : ℕ}
    (x : Image rows cols) :
    (twoLayerLeftBoundaryCarrierNetwork rows cols).eval x =
      expectedLeftBoundary (rows + 2 - 1) (cols + 2 - 1) 1 := by
  rw [twoLayerLeftBoundaryCarrierNetwork,
    SharedBiasNetworkTo.eval_cons, constant_seed (by norm_num) x,
    SharedBiasNetworkTo.eval_single]
  exact horizontal_boundary_signal (by norm_num)

/-- The left-boundary indicator generated by the two-layer network is
spatially nonuniform, for every input rectangle including empty ones. -/
theorem twoLayerLeftBoundaryCarrier_nonuniform (rows cols : ℕ) :
    SpatiallyNonuniform
      (expectedLeftBoundary (rows + 2 - 1) (cols + 2 - 1) 1) := by
  refine ⟨⟨0, by omega⟩, ⟨0, by omega⟩,
    ⟨0, by omega⟩, ⟨1, by omega⟩, ?_⟩
  simp [expectedLeftBoundary]

/-- Sharp carrier-initialization theorem.  On every input domain containing
zero, an input-independent nonuniform spatial carrier is realized by an
explicit network of exact depth two, while no single shared-bias layer can
realize any such carrier. -/
theorem nonuniform_inputIndependent_carrier_depth_two_sharp
    {rows cols : ℕ} (K : Set (Image rows cols))
    (hzero : (0 : Image rows cols) ∈ K) :
    (∃ (net : SharedBiasNetworkTo 2 2 rows cols
          ((rows + 2 - 1) + 2 - 1) ((cols + 2 - 1) + 2 - 1))
        (carrier : Image ((rows + 2 - 1) + 2 - 1)
          ((cols + 2 - 1) + 2 - 1)),
        net.net.depth = 2 ∧ SpatiallyNonuniform carrier ∧
          ∀ x ∈ K, net.eval x = carrier) ∧
      (∀ (w : Kernel 2 2) (b : ℝ),
        ¬ ∃ carrier : Image (rows + 2 - 1) (cols + 2 - 1),
          SpatiallyNonuniform carrier ∧
            ∀ x ∈ K, sharedLayerEval w b x = carrier) := by
  constructor
  · refine ⟨twoLayerLeftBoundaryCarrierNetwork rows cols,
      expectedLeftBoundary (rows + 2 - 1) (cols + 2 - 1) 1,
      twoLayerLeftBoundaryCarrierNetwork_depth rows cols,
      twoLayerLeftBoundaryCarrier_nonuniform rows cols, ?_⟩
    intro x _hx
    exact twoLayerLeftBoundaryCarrierNetwork_eval x
  · intro w b
    exact not_oneLayer_nonuniform_inputIndependent_on_zero_mem K hzero w b

/-- Concrete compact-domain form of the sharp theorem for the two-register
input box `[-M,M]²`. -/
theorem nonuniform_inputIndependent_carrier_depth_two_sharp_on_symmetricBox
    (M : ℝ) (hM : 0 ≤ M) :
    (∃ (net : SharedBiasNetworkTo 2 2 1 2
          ((1 + 2 - 1) + 2 - 1) ((2 + 2 - 1) + 2 - 1))
        (carrier : Image ((1 + 2 - 1) + 2 - 1) ((2 + 2 - 1) + 2 - 1)),
        net.net.depth = 2 ∧ SpatiallyNonuniform carrier ∧
          ∀ x ∈ twoPointSymmetricBox M, net.eval x = carrier) ∧
      (∀ (w : Kernel 2 2) (b : ℝ),
        ¬ ∃ carrier : Image (1 + 2 - 1) (2 + 2 - 1),
          SpatiallyNonuniform carrier ∧
            ∀ x ∈ twoPointSymmetricBox M,
              sharedLayerEval w b x = carrier) := by
  exact nonuniform_inputIndependent_carrier_depth_two_sharp
    (twoPointSymmetricBox M) (twoPointSymmetricBox_zero_mem M hM)

end OneChannelCNNUniversality
