import OneChannelCNNUniversality.SharedBiasSeedTransport

/-!
# Appending a protected selector after an existing shared-bias network

The successor feature is the northwest delta embedding of the preceding
network output.  A genuine seed layer realizes `successorFeature + c`, so the
compact protected-selection theorem can be applied again without inserting
any operation outside the CNN architecture.
-/

namespace OneChannelCNNUniversality

/-- The variable part presented to the next selection block after inserting
an expansive delta-identity bridge. -/
def successorFeature
    {X : Type*} {inRows inCols midRows midCols : ℕ}
    (head : SharedBiasNetworkTo 2 2 inRows inCols midRows midCols)
    (F : X → Image inRows inCols) :
    X → Image (midRows + 2 - 1) (midCols + 2 - 1) :=
  fun x ↦ fullConvImage expansiveIdentityKernel (head.eval (F x))

/-- Successor features remain coordinatewise continuous on the compact
input family. -/
theorem continuousFeatureOn_successorFeature
    {X : Type*} [TopologicalSpace X] {K : Set X}
    {inRows inCols midRows midCols : ℕ}
    (head : SharedBiasNetworkTo 2 2 inRows inCols midRows midCols)
    (F : X → Image inRows inCols) (hF : ContinuousFeatureOn K F) :
    ContinuousFeatureOn K (successorFeature head F) := by
  intro i j
  exact continuousFeatureOn_fullConv
    (head.continuousFeatureOn_eval F hF)
    expansiveIdentityKernel i j

/-- A protected Pascal selector can be appended after every positive-depth
shared-bias network.  The returned equality verifies that the entire path is
one genuine network: the fresh constant seed is generated by the internal
shared-bias bridge layer. -/
theorem exists_bundled_pascal_selection_after
    {X : Type*} [TopologicalSpace X] {K : Set X}
    (hK : IsCompact K) {inRows inCols midRows midCols : ℕ}
    (head : SharedBiasNetworkTo 2 2 inRows inCols midRows midCols)
    (hhead : 0 < head.net.depth)
    (F : X → Image inRows inCols) (hF : ContinuousFeatureOn K F)
    (rowSteps extraColSteps : ℕ)
    (targetRow : Fin (midRows + 2 - 1))
    (targetCol : Fin (midCols + 2 - 1)) (θ : ℝ)
    (hrowSteps : (midRows + 2 - 1) - 1 ≤ rowSteps)
    (hcolSteps : (midCols + 2 - 1) - 1 ≤ extraColSteps + 1) :
    ∃ c b : ℝ, ∃ tail : SharedBiasNetworkTo 2 2
        (midRows + 2 - 1) (midCols + 2 - 1)
        (grownSize 2
          (grownSize 2 ((midRows + 2 - 1) + 2 - 1)
            extraColSteps) rowSteps + 2 - 1)
        (grownSize 2
          (grownSize 2 ((midCols + 2 - 1) + 2 - 1)
            extraColSteps) rowSteps + 2 - 1),
      0 < c ∧ 0 < b ∧
      BundledPascalGridSelectionSpec K (successorFeature head F) θ
        rowSteps extraColSteps targetRow targetCol c b tail ∧
      ∀ x ∈ K,
        (head.appendWithSeed c tail).eval (F x) =
          tail.eval
            (successorFeature head F x +
              constantImage (midRows + 2 - 1) (midCols + 2 - 1) c) := by
  obtain ⟨c, b, tail, hc, hb, _hdepth, hspec⟩ :=
    exists_bundled_pascal_grid_protected_selection hK
      (successorFeature head F)
      (continuousFeatureOn_successorFeature head F hF)
      rowSteps extraColSteps targetRow targetCol θ hrowSteps hcolSteps
  refine ⟨c, b, tail, hc, hb, hspec, ?_⟩
  intro x hx
  exact head.eval_appendWithSeed_of_nonnegative tail
    (head.eval_nonnegative_of_pos_depth (F x) hhead) hc.le

/-- Output side length of one protected Pascal selection block. -/
abbrev protectedSelectionSize (n rowSteps extraColSteps : ℕ) : ℕ :=
  grownSize 2 (grownSize 2 (n + 2 - 1) extraColSteps) rowSteps + 2 - 1

/-- Two compact protected selections can be realized consecutively by one
shared-bias CNN.  The second seed is an actual internal layer, not an
external modification of the intermediate feature image. -/
theorem exists_two_bundled_pascal_selection_stages
    {X : Type*} [TopologicalSpace X] {K : Set X} (hK : IsCompact K)
    {rows cols : ℕ} (V : X → Image rows cols)
    (hV : ContinuousFeatureOn K V)
    (rowSteps₁ extraColSteps₁ : ℕ)
    (targetRow₁ : Fin rows) (targetCol₁ : Fin cols) (θ₁ : ℝ)
    (hrowSteps₁ : rows - 1 ≤ rowSteps₁)
    (hcolSteps₁ : cols - 1 ≤ extraColSteps₁ + 1)
    (rowSteps₂ extraColSteps₂ : ℕ)
    (targetRow₂ : Fin
      (protectedSelectionSize rows rowSteps₁ extraColSteps₁ + 2 - 1))
    (targetCol₂ : Fin
      (protectedSelectionSize cols rowSteps₁ extraColSteps₁ + 2 - 1))
    (θ₂ : ℝ)
    (hrowSteps₂ :
      (protectedSelectionSize rows rowSteps₁ extraColSteps₁ + 2 - 1) - 1 ≤
        rowSteps₂)
    (hcolSteps₂ :
      (protectedSelectionSize cols rowSteps₁ extraColSteps₁ + 2 - 1) - 1 ≤
        extraColSteps₂ + 1) :
    ∃ c₁ b₁ : ℝ, ∃ head : SharedBiasNetworkTo 2 2 rows cols
        (protectedSelectionSize rows rowSteps₁ extraColSteps₁)
        (protectedSelectionSize cols rowSteps₁ extraColSteps₁),
      0 < c₁ ∧ 0 < b₁ ∧
      head.net.depth = rowSteps₁ + extraColSteps₁ + 2 ∧
      BundledPascalGridSelectionSpec K V θ₁ rowSteps₁ extraColSteps₁
        targetRow₁ targetCol₁ c₁ b₁ head ∧
      ∃ c₂ b₂ : ℝ, ∃ tail : SharedBiasNetworkTo 2 2
          (protectedSelectionSize rows rowSteps₁ extraColSteps₁ + 2 - 1)
          (protectedSelectionSize cols rowSteps₁ extraColSteps₁ + 2 - 1)
          (protectedSelectionSize
            (protectedSelectionSize rows rowSteps₁ extraColSteps₁ + 2 - 1)
            rowSteps₂ extraColSteps₂)
          (protectedSelectionSize
            (protectedSelectionSize cols rowSteps₁ extraColSteps₁ + 2 - 1)
            rowSteps₂ extraColSteps₂),
        0 < c₂ ∧ 0 < b₂ ∧
        BundledPascalGridSelectionSpec K
          (successorFeature head
            (fun x ↦ V x + constantImage rows cols c₁))
          θ₂ rowSteps₂ extraColSteps₂ targetRow₂ targetCol₂ c₂ b₂ tail ∧
        ∀ x ∈ K,
          (head.appendWithSeed c₂ tail).eval
              (V x + constantImage rows cols c₁) =
            tail.eval
              (successorFeature head
                  (fun y ↦ V y + constantImage rows cols c₁) x +
                constantImage
                  (protectedSelectionSize rows rowSteps₁ extraColSteps₁ +
                    2 - 1)
                  (protectedSelectionSize cols rowSteps₁ extraColSteps₁ +
                    2 - 1) c₂) := by
  obtain ⟨c₁, b₁, head, hc₁, hb₁, hdepth₁, hspec₁⟩ :=
    exists_bundled_pascal_grid_protected_selection hK V hV
      rowSteps₁ extraColSteps₁ targetRow₁ targetCol₁ θ₁
      hrowSteps₁ hcolSteps₁
  have hseeded : ContinuousFeatureOn K
      (fun x ↦ V x + constantImage rows cols c₁) := by
    intro i j
    exact (hV i j).add continuousOn_const
  have hhead : 0 < head.net.depth := by omega
  obtain ⟨c₂, b₂, tail, hc₂, hb₂, hspec₂, heval₂⟩ :=
    exists_bundled_pascal_selection_after hK head hhead
      (fun x ↦ V x + constantImage rows cols c₁) hseeded
      rowSteps₂ extraColSteps₂ targetRow₂ targetCol₂ θ₂
      hrowSteps₂ hcolSteps₂
  exact ⟨c₁, b₁, head, hc₁, hb₁, hdepth₁, hspec₁,
    c₂, b₂, tail, hc₂, hb₂, hspec₂, heval₂⟩

end OneChannelCNNUniversality
