import ICM2022NumCS97.Ridge
import Mathlib.Topology.ContinuousMap.StoneWeierstrass

/-!
# Axiom-free lattice density on compact image sets

Finite lattice expressions generated by affine functions form a nonempty
point-separating sublattice of the continuous real functions.  Mathlib's
kernel-checked lattice Stone--Weierstrass theorem therefore gives uniform
density.  A later module compiles these expressions into the verified
single-channel register machine.
-/

namespace ICM2022NumCS97

inductive LatticeExpr (d₁ d₂ : ℕ)
  | affine (weight : Image d₁ d₂) (constant : ℝ)
  | min (left right : LatticeExpr d₁ d₂)
  | max (left right : LatticeExpr d₁ d₂)

namespace LatticeExpr

def eval {d₁ d₂ : ℕ} : LatticeExpr d₁ d₂ → Image d₁ d₂ → ℝ
  | .affine weight constant, x =>
      (∑ i, ∑ j, weight i j * x i j) + constant
  | .min left right, x => Min.min (left.eval x) (right.eval x)
  | .max left right, x => Max.max (left.eval x) (right.eval x)

theorem continuous_eval {d₁ d₂ : ℕ} (e : LatticeExpr d₁ d₂) :
    Continuous e.eval := by
  induction e with
  | affine weight constant =>
      simp only [eval]
      fun_prop
  | min left right hleft hright =>
      simpa only [eval] using hleft.min hright
  | max left right hleft hright =>
      simpa only [eval] using hleft.max hright

def toContinuousMap {d₁ d₂ : ℕ} (e : LatticeExpr d₁ d₂) :
    C(Image d₁ d₂, ℝ) :=
  ⟨e.eval, e.continuous_eval⟩

def toContinuousMapOn {d₁ d₂ : ℕ} (e : LatticeExpr d₁ d₂)
    (K : Set (Image d₁ d₂)) : C(K, ℝ) :=
  ⟨fun x ↦ e.eval x.1, e.continuous_eval.comp continuous_subtype_val⟩

@[simp] theorem toContinuousMapOn_apply {d₁ d₂ : ℕ}
    (e : LatticeExpr d₁ d₂) (K : Set (Image d₁ d₂)) (x : K) :
    e.toContinuousMapOn K x = e.eval x.1 := rfl

def coordinateAffine {d₁ d₂ : ℕ} (i : Fin d₁) (j : Fin d₂)
    (slope constant : ℝ) : LatticeExpr d₁ d₂ :=
  .affine (fun r c ↦ if r = i then if c = j then slope else 0 else 0) constant

@[simp] theorem coordinateAffine_eval {d₁ d₂ : ℕ}
    (i : Fin d₁) (j : Fin d₂) (slope constant : ℝ)
    (x : Image d₁ d₂) :
    (coordinateAffine i j slope constant).eval x =
      slope * x i j + constant := by
  classical
  simp [coordinateAffine, eval]

/-- Evaluate the same lattice syntax on the separated coordinates produced by
the certified sparse encoder.  These are the coordinates that the register
machine can read directly. -/
def evalEncoded {d₁ d₂ : ℕ} : LatticeExpr d₁ d₂ → Image d₁ d₂ → ℝ
  | .affine weight constant, x =>
      (∑ i, ∑ j, weight i j * sparseEncodedValue x i j) + constant
  | .min left right, x => Min.min (left.evalEncoded x) (right.evalEncoded x)
  | .max left right, x => Max.max (left.evalEncoded x) (right.evalEncoded x)

theorem continuous_evalEncoded {d₁ d₂ : ℕ} (e : LatticeExpr d₁ d₂) :
    Continuous e.evalEncoded := by
  induction e with
  | affine weight constant =>
      simp only [evalEncoded, sparseEncodedValue]
      fun_prop
  | min left right hleft hright =>
      simpa only [evalEncoded] using hleft.min hright
  | max left right hleft hright =>
      simpa only [evalEncoded] using hleft.max hright

def toEncodedContinuousMapOn {d₁ d₂ : ℕ} (e : LatticeExpr d₁ d₂)
    (K : Set (Image d₁ d₂)) : C(K, ℝ) :=
  ⟨fun x ↦ e.evalEncoded x.1,
    e.continuous_evalEncoded.comp continuous_subtype_val⟩

@[simp] theorem toEncodedContinuousMapOn_apply {d₁ d₂ : ℕ}
    (e : LatticeExpr d₁ d₂) (K : Set (Image d₁ d₂)) (x : K) :
    e.toEncodedContinuousMapOn K x = e.evalEncoded x.1 := rfl

@[simp] theorem coordinateAffine_evalEncoded {d₁ d₂ : ℕ}
    (i : Fin d₁) (j : Fin d₂) (slope constant : ℝ)
    (x : Image d₁ d₂) :
    (coordinateAffine i j slope constant).evalEncoded x =
      slope * sparseEncodedValue x i j + constant := by
  classical
  simp [coordinateAffine, evalEncoded]

end LatticeExpr

def latticeFunctions {d₁ d₂ : ℕ} (K : Set (Image d₁ d₂)) :
    Set C(K, ℝ) :=
  Set.range (fun e : LatticeExpr d₁ d₂ ↦ e.toContinuousMapOn K)

theorem latticeFunctions_nonempty {d₁ d₂ : ℕ}
    (K : Set (Image d₁ d₂)) : (latticeFunctions K).Nonempty := by
  refine ⟨(LatticeExpr.affine 0 0).toContinuousMapOn K, ?_⟩
  exact ⟨.affine 0 0, rfl⟩

theorem latticeFunctions_inf_mem {d₁ d₂ : ℕ}
    (K : Set (Image d₁ d₂)) :
    ∀ᵉ (f ∈ latticeFunctions K) (g ∈ latticeFunctions K),
      f ⊓ g ∈ latticeFunctions K := by
  rintro f ⟨left, rfl⟩ g ⟨right, rfl⟩
  refine ⟨.min left right, ?_⟩
  ext x
  simp [LatticeExpr.eval]

theorem latticeFunctions_sup_mem {d₁ d₂ : ℕ}
    (K : Set (Image d₁ d₂)) :
    ∀ᵉ (f ∈ latticeFunctions K) (g ∈ latticeFunctions K),
      f ⊔ g ∈ latticeFunctions K := by
  rintro f ⟨left, rfl⟩ g ⟨right, rfl⟩
  refine ⟨.max left right, ?_⟩
  ext x
  simp [LatticeExpr.eval]

theorem latticeFunctions_separates_strongly {d₁ d₂ : ℕ}
    (K : Set (Image d₁ d₂)) :
    (latticeFunctions K).SeparatesPointsStrongly := by
  intro v x y
  by_cases hxy : x = y
  · subst y
    let e : LatticeExpr d₁ d₂ := .affine 0 (v x)
    refine ⟨e.toContinuousMapOn K, ⟨e, rfl⟩, ?_, ?_⟩
    · simp [e, LatticeExpr.eval]
    · simp [e, LatticeExpr.eval]
  · have hval : x.1 ≠ y.1 := by
      intro h
      exact hxy (Subtype.ext h)
    obtain ⟨i, hi⟩ := Function.ne_iff.mp hval
    obtain ⟨j, hij⟩ := Function.ne_iff.mp hi
    let denominator := y.1 i j - x.1 i j
    have hdenominator : denominator ≠ 0 := by
      exact sub_ne_zero.mpr hij.symm
    let slope := (v y - v x) / denominator
    let constant := v x - slope * x.1 i j
    let e := LatticeExpr.coordinateAffine i j slope constant
    refine ⟨e.toContinuousMapOn K, ⟨e, rfl⟩, ?_, ?_⟩
    · simp only [LatticeExpr.toContinuousMapOn_apply, e,
        LatticeExpr.coordinateAffine_eval]
      dsimp [constant]
      ring
    · simp only [LatticeExpr.toContinuousMapOn_apply, e,
        LatticeExpr.coordinateAffine_eval]
      dsimp [constant, slope, denominator]
      field_simp [hdenominator]
      ring

/-- Uniform density of finite affine lattice expressions on every compact
set of finite images. -/
theorem latticeExpr_dense_on_compact {d₁ d₂ : ℕ}
    {K : Set (Image d₁ d₂)} (hK : IsCompact K)
    (f : C(K, ℝ)) {ε : ℝ} (hε : 0 < ε) :
    ∃ e : LatticeExpr d₁ d₂,
      ∀ x : K, |e.eval x.1 - f x| < ε := by
  letI : CompactSpace K := isCompact_iff_compactSpace.mp hK
  let L := latticeFunctions K
  have hclosure : closure L = (Set.univ : Set C(K, ℝ)) :=
    ContinuousMap.sublattice_closure_eq_top L
      (latticeFunctions_nonempty K)
      (latticeFunctions_inf_mem K)
      (latticeFunctions_sup_mem K)
      (latticeFunctions_separates_strongly K)
  have hf : f ∈ closure L := by
    rw [hclosure]
    trivial
  obtain ⟨g, hgL, hdist⟩ := (Metric.mem_closure_iff.mp hf) ε hε
  obtain ⟨e, rfl⟩ := hgL
  refine ⟨e, ?_⟩
  intro x
  have hpoint := ContinuousMap.dist_apply_le_dist
    (f := e.toContinuousMapOn K) (g := f) x
  have hdist' : dist (e.toContinuousMapOn K) f < ε := by
    simpa [dist_comm] using hdist
  have hlt : dist (e.toContinuousMapOn K x) (f x) < ε :=
    hpoint.trans_lt hdist'
  simpa [Real.dist_eq] using hlt

/-- Lattice functions expressed in the actual sparse-encoder coordinates. -/
def encodedLatticeFunctions {d₁ d₂ : ℕ} (K : Set (Image d₁ d₂)) :
    Set C(K, ℝ) :=
  Set.range (fun e : LatticeExpr d₁ d₂ ↦
    e.toEncodedContinuousMapOn K)

theorem encodedLatticeFunctions_nonempty {d₁ d₂ : ℕ}
    (K : Set (Image d₁ d₂)) :
    (encodedLatticeFunctions K).Nonempty := by
  refine ⟨(LatticeExpr.affine 0 0).toEncodedContinuousMapOn K, ?_⟩
  exact ⟨.affine 0 0, rfl⟩

theorem encodedLatticeFunctions_inf_mem {d₁ d₂ : ℕ}
    (K : Set (Image d₁ d₂)) :
    ∀ᵉ (f ∈ encodedLatticeFunctions K) (g ∈ encodedLatticeFunctions K),
      f ⊓ g ∈ encodedLatticeFunctions K := by
  rintro f ⟨left, rfl⟩ g ⟨right, rfl⟩
  refine ⟨.min left right, ?_⟩
  ext x
  simp [LatticeExpr.evalEncoded]

theorem encodedLatticeFunctions_sup_mem {d₁ d₂ : ℕ}
    (K : Set (Image d₁ d₂)) :
    ∀ᵉ (f ∈ encodedLatticeFunctions K) (g ∈ encodedLatticeFunctions K),
      f ⊔ g ∈ encodedLatticeFunctions K := by
  rintro f ⟨left, rfl⟩ g ⟨right, rfl⟩
  refine ⟨.max left right, ?_⟩
  ext x
  simp [LatticeExpr.evalEncoded]

theorem encodedLatticeFunctions_separates_strongly {d₁ d₂ : ℕ}
    (hd₁ : 0 < d₁) (hd₂ : 0 < d₂) (K : Set (Image d₁ d₂)) :
    (encodedLatticeFunctions K).SeparatesPointsStrongly := by
  intro v x y
  by_cases hxy : x = y
  · subst y
    let e : LatticeExpr d₁ d₂ := .affine 0 (v x)
    refine ⟨e.toEncodedContinuousMapOn K, ⟨e, rfl⟩, ?_, ?_⟩
    · simp [e, LatticeExpr.evalEncoded]
    · simp [e, LatticeExpr.evalEncoded]
  · have hval : x.1 ≠ y.1 := by
      intro h
      exact hxy (Subtype.ext h)
    have hencoded : sparseEncodedMatrix x.1 ≠ sparseEncodedMatrix y.1 := by
      intro h
      exact hval (sparseEncodedMatrix_injective hd₁ hd₂ h)
    obtain ⟨i, hi⟩ := Function.ne_iff.mp hencoded
    obtain ⟨j, hij⟩ := Function.ne_iff.mp hi
    let denominator := sparseEncodedValue y.1 i j -
      sparseEncodedValue x.1 i j
    have hdenominator : denominator ≠ 0 := by
      exact sub_ne_zero.mpr hij.symm
    let slope := (v y - v x) / denominator
    let constant := v x - slope * sparseEncodedValue x.1 i j
    let e := LatticeExpr.coordinateAffine i j slope constant
    refine ⟨e.toEncodedContinuousMapOn K, ⟨e, rfl⟩, ?_, ?_⟩
    · simp only [LatticeExpr.toEncodedContinuousMapOn_apply, e,
        LatticeExpr.coordinateAffine_evalEncoded]
      dsimp [constant]
      ring
    · simp only [LatticeExpr.toEncodedContinuousMapOn_apply, e,
        LatticeExpr.coordinateAffine_evalEncoded]
      have hslope : slope * denominator = v y - v x := by
        dsimp [slope]
        exact div_mul_cancel₀ _ hdenominator
      dsimp only [constant]
      calc
        slope * sparseEncodedValue y.1 i j +
              (v x - slope * sparseEncodedValue x.1 i j) =
            v x + slope * denominator := by
              dsimp [denominator]
              ring
        _ = v x + (v y - v x) := by rw [hslope]
        _ = v y := by ring

/-- Uniform density after replacing raw pixels by the exact separated
encoder coordinates.  Injectivity of the encoder is the only additional
ingredient. -/
theorem encodedLatticeExpr_dense_on_compact {d₁ d₂ : ℕ}
    (hd₁ : 0 < d₁) (hd₂ : 0 < d₂)
    {K : Set (Image d₁ d₂)} (hK : IsCompact K)
    (f : C(K, ℝ)) {ε : ℝ} (hε : 0 < ε) :
    ∃ e : LatticeExpr d₁ d₂,
      ∀ x : K, |e.evalEncoded x.1 - f x| < ε := by
  letI : CompactSpace K := isCompact_iff_compactSpace.mp hK
  let L := encodedLatticeFunctions K
  have hclosure : closure L = (Set.univ : Set C(K, ℝ)) :=
    ContinuousMap.sublattice_closure_eq_top L
      (encodedLatticeFunctions_nonempty K)
      (encodedLatticeFunctions_inf_mem K)
      (encodedLatticeFunctions_sup_mem K)
      (encodedLatticeFunctions_separates_strongly hd₁ hd₂ K)
  have hf : f ∈ closure L := by
    rw [hclosure]
    trivial
  obtain ⟨g, hgL, hdist⟩ := (Metric.mem_closure_iff.mp hf) ε hε
  obtain ⟨e, rfl⟩ := hgL
  refine ⟨e, ?_⟩
  intro x
  have hpoint := ContinuousMap.dist_apply_le_dist
    (f := e.toEncodedContinuousMapOn K) (g := f) x
  have hdist' : dist (e.toEncodedContinuousMapOn K) f < ε := by
    simpa [dist_comm] using hdist
  have hlt : dist (e.toEncodedContinuousMapOn K x) (f x) < ε :=
    hpoint.trans_lt hdist'
  simpa [Real.dist_eq] using hlt

end ICM2022NumCS97
