import OneChannelCNNUniversality.SharedBiasAddress

#print axioms OneChannelCNNUniversality.exists_shared_bias_carrier_layer
#print axioms OneChannelCNNUniversality.horizontalBoundaryTransform_injective
#print axioms OneChannelCNNUniversality.horizontalSharedCarrier_left
#print axioms OneChannelCNNUniversality.horizontalSharedCarrier_interior
#print axioms OneChannelCNNUniversality.exists_horizontal_shared_carrier_layer
#print axioms OneChannelCNNUniversality.sharedLayer_select_target_of_carrier_gap
#print axioms OneChannelCNNUniversality.exists_uniform_feature_margin
#print axioms OneChannelCNNUniversality.exists_sharedBias_select_from_unit_address
#print axioms OneChannelCNNUniversality.sharedBiasSelectiveActivation_on
#print axioms OneChannelCNNUniversality.protectedNorthwestAddress_gap
#print axioms OneChannelCNNUniversality.northwestAddressCarrier_gap_on
#print axioms OneChannelCNNUniversality.twoLayerAccumulationTransform_injective
#print axioms OneChannelCNNUniversality.exists_northwest_address_layers
#print axioms OneChannelCNNUniversality.exists_northwest_protected_selection_layers
