import OneChannelCNNUniversality.SharedBiasChainSelection
import OneChannelCNNUniversality.SharedBiasSuccessorSelection
import OneChannelCNNUniversality.SharedBiasTwoStageRecovery
import OneChannelCNNUniversality.SharedBiasFiniteRecovery
import OneChannelCNNUniversality.SharedBiasFiniteSelection
import OneChannelCNNUniversality.SharedBiasScheduledRecovery
import OneChannelCNNUniversality.SharedBiasProtectionObstruction
import OneChannelCNNUniversality.SharedBiasRedundantRecovery
import OneChannelCNNUniversality.SharedBiasAdjacentCopy
import OneChannelCNNUniversality.SharedBiasMonotoneCode
import OneChannelCNNUniversality.SharedBiasMonotoneSchedule
import OneChannelCNNUniversality.SharedBiasFrontier
import OneChannelCNNUniversality.SharedBiasFrontierChain
import OneChannelCNNUniversality.SharedBiasFrontierTurn
import OneChannelCNNUniversality.SharedBiasFrontierRoute

#print axioms OneChannelCNNUniversality.exists_shared_bias_carrier_layer
#print axioms OneChannelCNNUniversality.horizontalBoundaryTransform_injective
#print axioms OneChannelCNNUniversality.horizontalSharedCarrier_left
#print axioms OneChannelCNNUniversality.horizontalSharedCarrier_interior
#print axioms OneChannelCNNUniversality.exists_horizontal_shared_carrier_layer
#print axioms OneChannelCNNUniversality.sharedLayer_select_target_of_carrier_gap
#print axioms OneChannelCNNUniversality.exists_uniform_feature_margin
#print axioms OneChannelCNNUniversality.exists_sharedBias_select_from_unit_address
#print axioms OneChannelCNNUniversality.sharedBiasSelectiveActivation_on
#print axioms OneChannelCNNUniversality.protectedNorthwestAddress_gap
#print axioms OneChannelCNNUniversality.northwestAddressCarrier_gap_on
#print axioms OneChannelCNNUniversality.twoLayerAccumulationTransform_injective
#print axioms OneChannelCNNUniversality.exists_northwest_address_layers
#print axioms OneChannelCNNUniversality.exists_northwest_protected_selection_layers
#print axioms OneChannelCNNUniversality.pascalPrefix_gap
#print axioms OneChannelCNNUniversality.protectedHorizontalScanAddress_eq
#print axioms OneChannelCNNUniversality.exists_horizontal_suffix_selected_relu
#print axioms OneChannelCNNUniversality.protectedPascalGridAddress_eq
#print axioms OneChannelCNNUniversality.pascalGridTransform_injective
#print axioms OneChannelCNNUniversality.exists_southeast_selected_relu
#print axioms OneChannelCNNUniversality.exists_shared_bias_full_iterations
#print axioms OneChannelCNNUniversality.exists_shared_bias_pascal_grid_layers
#print axioms OneChannelCNNUniversality.zeroBiasPascalGridNetwork_eval_of_nonnegative
#print axioms OneChannelCNNUniversality.exists_sharedLayer_southeast_pascal_selection
#print axioms OneChannelCNNUniversality.protectedLinearizedPascalCarrier_eq
#print axioms OneChannelCNNUniversality.protectedLinearizedPascalCarrier_gap_on
#print axioms OneChannelCNNUniversality.exists_pascal_grid_protected_selection_layers
#print axioms OneChannelCNNUniversality.SharedBiasNetworkTo.eval_append
#print axioms OneChannelCNNUniversality.pascalGridSelectionNetwork_eval
#print axioms OneChannelCNNUniversality.exists_bundled_pascal_grid_protected_selection
#print axioms OneChannelCNNUniversality.northwestAgree_fullConvImage
#print axioms OneChannelCNNUniversality.northwestAgree_sharedLayerEval
#print axioms OneChannelCNNUniversality.northwestAgree_iterateFullConv
#print axioms OneChannelCNNUniversality.northwestAgree_sharedBiasNetwork_eval
#print axioms OneChannelCNNUniversality.northwestAgree_sharedBiasNetworkTo_eval
#print axioms OneChannelCNNUniversality.protectedLinearizedPascalSignal_eq_of_northwestAgree
#print axioms OneChannelCNNUniversality.fullConvImage_smul
#print axioms OneChannelCNNUniversality.iterateFullConv_smul
#print axioms OneChannelCNNUniversality.linearReadoutWeights_apply
#print axioms OneChannelCNNUniversality.pascalGridLinearMap_injective
#print axioms OneChannelCNNUniversality.pascalGridLeftInverse_apply
#print axioms OneChannelCNNUniversality.exists_pascalGrid_coordinate_readout
#print axioms OneChannelCNNUniversality.exists_zeroBiasPascalGridNetwork_coordinate_readout
#print axioms OneChannelCNNUniversality.agreeOutsideSoutheast_fullConvImage
#print axioms OneChannelCNNUniversality.agreeOutsideSoutheast_sharedLayerEval
#print axioms OneChannelCNNUniversality.agreeOutsideSoutheast_sharedBiasNetwork_eval
#print axioms OneChannelCNNUniversality.agreeOutsideSoutheast_sharedBiasNetworkTo_eval
#print axioms OneChannelCNNUniversality.AgreeOutsideStrictSoutheast.northwestAgree
#print axioms OneChannelCNNUniversality.agreeOutsideStrictSoutheast_sharedBiasNetwork_eval
#print axioms OneChannelCNNUniversality.agreeOutsideStrictSoutheast_sharedBiasNetworkTo_eval
#print axioms OneChannelCNNUniversality.northwestAgree_of_horizontalAccumulation
#print axioms OneChannelCNNUniversality.northwestAgree_of_verticalAccumulation
#print axioms OneChannelCNNUniversality.protectedLinearizedPascalSignal_injective
#print axioms OneChannelCNNUniversality.agreeOutsideSoutheast_linearizedPascalSignal
#print axioms OneChannelCNNUniversality.BundledPascalGridSelectionSpec.injective_on_rootPuncturedSoutheast
#print axioms OneChannelCNNUniversality.not_surjective_of_southeastMonotoneLayout
#print axioms OneChannelCNNUniversality.SoutheastMonotoneLayout.length_le
#print axioms OneChannelCNNUniversality.rowMajorChainDecode_encode
#print axioms OneChannelCNNUniversality.rowMajorChainEncode_injective
#print axioms OneChannelCNNUniversality.rowPrefixAgree_iff_agreeOutsideStrictSoutheast
#print axioms OneChannelCNNUniversality.BundledRowChainSelectionSpec.injective_of_rowPrefixAgree
#print axioms OneChannelCNNUniversality.exists_bundled_rowChain_protected_selection
#print axioms OneChannelCNNUniversality.sharedBiasSeedLayer_eval_of_nonnegative
#print axioms OneChannelCNNUniversality.SharedBiasNetworkTo.eval_appendWithSeed_of_nonnegative
#print axioms OneChannelCNNUniversality.exists_bundled_pascal_selection_after
#print axioms OneChannelCNNUniversality.exists_two_bundled_pascal_selection_stages
#print axioms OneChannelCNNUniversality.fullConvImage_expansiveIdentityKernel_injective
#print axioms OneChannelCNNUniversality.agreeOutsideStrictSoutheast_successorFeature
#print axioms OneChannelCNNUniversality.twoStage_pascal_selection_injective_on_rootPuncturedSoutheast
#print axioms OneChannelCNNUniversality.RelativeRecoveryChain.recover
#print axioms OneChannelCNNUniversality.RelativeRecoveryChain.length_append
#print axioms OneChannelCNNUniversality.RelativeRecoveryChain.protected_append_iff
#print axioms OneChannelCNNUniversality.twoStageRecoveryChain
#print axioms OneChannelCNNUniversality.CompiledSuccessorSelectionSchedule.finalNetwork
#print axioms OneChannelCNNUniversality.exists_compiledSuccessorSelectionSchedule
#print axioms OneChannelCNNUniversality.appendedSelectionRecoveryStep
#print axioms OneChannelCNNUniversality.CompiledSuccessorSelectionSchedule.recoveryChain
#print axioms OneChannelCNNUniversality.CompiledSuccessorSelectionSchedule.length_recoveryChain
#print axioms OneChannelCNNUniversality.CompiledSuccessorSelectionSchedule.recover_headEval
#print axioms OneChannelCNNUniversality.CompiledSuccessorSelectionSchedule.finalNetwork_injectiveOn
#print axioms OneChannelCNNUniversality.PairwiseStrictSoutheastProtectedOn.targetCoordinate_constant
#print axioms OneChannelCNNUniversality.not_pairwiseStrictSoutheastProtectedOn_of_target_ne
#print axioms OneChannelCNNUniversality.TargetCoordinateConstantOn.selectedReLU_constant
#print axioms OneChannelCNNUniversality.pairwise_appendedSelection_protection_forces_target_constant
#print axioms OneChannelCNNUniversality.not_pairwise_appendedSelection_protection_of_target_ne
#print axioms OneChannelCNNUniversality.protectedLinearizedPascalSignal_rowZero_zero
#print axioms OneChannelCNNUniversality.protectedLinearizedPascalSignal_rowZero_one
#print axioms OneChannelCNNUniversality.BundledPascalGridSelectionSpec.injective_on_eastRootDuplicate
#print axioms OneChannelCNNUniversality.protectedLinearizedPascalSignal_northwest_zero
#print axioms OneChannelCNNUniversality.protectedLinearizedPascalSignal_northwest_one
#print axioms OneChannelCNNUniversality.adjacentCopyLayer_eval_of_nonnegative
#print axioms OneChannelCNNUniversality.adjacentCopyLayer_eastRootDuplicate
#print axioms OneChannelCNNUniversality.adjacentCopyLayer_injective_of_nonnegative
#print axioms OneChannelCNNUniversality.EastRootDuplicate.successorFeature
#print axioms OneChannelCNNUniversality.exists_injective_adjacentCopy_selection
#print axioms OneChannelCNNUniversality.NorthwestMonotoneCodeOn.expansiveIdentity
#print axioms OneChannelCNNUniversality.NorthwestMonotoneCodeOn.of_eqOn
#print axioms OneChannelCNNUniversality.northwestMonotoneCodeOn_successor_adjacentCopy
#print axioms OneChannelCNNUniversality.BundledPascalGridSelectionSpec.eval_northwest_zero
#print axioms OneChannelCNNUniversality.BundledPascalGridSelectionSpec.eval_northwest_one
#print axioms OneChannelCNNUniversality.BundledPascalGridSelectionSpec.injective_on_northwestMonotoneCode
#print axioms OneChannelCNNUniversality.BundledPascalGridSelectionSpec.preserves_northwestMonotoneCode
#print axioms OneChannelCNNUniversality.SharedBiasNetworkTo.appendWithSeed_preserves_northwestMonotoneCode
#print axioms OneChannelCNNUniversality.SharedBiasNetworkTo.appendWithSeed_injectiveOn_of_northwestMonotoneCode
#print axioms OneChannelCNNUniversality.northwestMonotoneCodeOn_adjacentCopy
#print axioms OneChannelCNNUniversality.two_le_protectedSelectionSize
#print axioms OneChannelCNNUniversality.CompiledSuccessorSelectionSchedule.preserves_northwestMonotoneCode
#print axioms OneChannelCNNUniversality.CompiledSuccessorSelectionSchedule.finalNetwork_injectiveOn_of_northwestMonotoneCode
#print axioms OneChannelCNNUniversality.CompiledSuccessorSelectionSchedule.monotoneCode_and_injectiveOn
#print axioms OneChannelCNNUniversality.exists_injective_compiledNorthwestSchedule
#print axioms OneChannelCNNUniversality.northwestOutput_eq_of_inputRoot_eq
#print axioms OneChannelCNNUniversality.NorthwestRealizesOn.eq_of_inputRoot_eq
#print axioms OneChannelCNNUniversality.not_exists_northwestRealization_of_root_eq_target_ne
#print axioms OneChannelCNNUniversality.northwest_two_point_error_lower_bound
#print axioms OneChannelCNNUniversality.not_exists_northwestApproximation_of_error_lt_half_gap
#print axioms OneChannelCNNUniversality.eastFrontierLayer_east_eval
#print axioms OneChannelCNNUniversality.eastFrontierLayer_injectiveOn_and_east_add
#print axioms OneChannelCNNUniversality.iteratePairKernel_frontierInvariant
#print axioms OneChannelCNNUniversality.iterateHorizontalAccumulation_frontierInvariant
#print axioms OneChannelCNNUniversality.horizontalFrontierNetwork_eval_of_nonnegative
#print axioms OneChannelCNNUniversality.horizontalFrontierNetwork_injectiveOn_and_invariant
#print axioms OneChannelCNNUniversality.iteratePairKernel_eq_zero_of_eq_zero
#print axioms OneChannelCNNUniversality.iterateHorizontalAccumulation_southRowsVacant
#print axioms OneChannelCNNUniversality.iteratePascalGrid_frontierInvariant
#print axioms OneChannelCNNUniversality.twoDimensionalFrontierNetwork_depth
#print axioms OneChannelCNNUniversality.twoDimensionalFrontierNetwork_eval_of_nonnegative
#print axioms OneChannelCNNUniversality.twoDimensionalFrontierNetwork_injectiveOn_and_invariant
#print axioms OneChannelCNNUniversality.eastStepCount_add_southStepCount
#print axioms OneChannelCNNUniversality.fullConvImage_horizontal_vertical_commute
#print axioms OneChannelCNNUniversality.iterateHorizontal_fullConvVertical_commute
#print axioms OneChannelCNNUniversality.applyFrontierRoute_eq_pascalGrid
#print axioms OneChannelCNNUniversality.applyFrontierRoute_injective
#print axioms OneChannelCNNUniversality.frontierRouteNetwork_depth
#print axioms OneChannelCNNUniversality.frontierRouteNetwork_eval_of_nonnegative
#print axioms OneChannelCNNUniversality.applyFrontierRoute_frontierInvariant
#print axioms OneChannelCNNUniversality.frontierRouteNetwork_injectiveOn_and_invariant
