import OneChannelCNNUniversality.SharedBiasParallelStripeInitializationObstruction

namespace OneChannelCNNUniversality

#check parallelStripeLoadedAffineInput
#check exists_parallelStripePackedAffineNetwork_on_compact_loaded
#check parallelStripeZeroWeights
#check parallelStripeObstructingOffsets
#check parallelStripeLoadedAffineInput_obstructing_southwest
#check parallelStripeLoadedAffineInput_obstructing_southwest_neg
#check not_exists_positiveDepth_parallelStripe_initializer_at
#check not_exists_positiveDepth_parallelStripe_initializer_on_nonempty

#print axioms parallelStripeLoadedAffineInput_obstructing_southwest
#print axioms exists_parallelStripePackedAffineNetwork_on_compact_loaded
#print axioms parallelStripeLoadedAffineInput_obstructing_southwest_neg
#print axioms not_exists_positiveDepth_parallelStripe_initializer_at
#print axioms not_exists_positiveDepth_parallelStripe_initializer_on_nonempty

end OneChannelCNNUniversality
