import OneChannelCNNUniversality.SharedBiasCarrier
import OneChannelCNNUniversality.SharedBiasSelection

#print axioms OneChannelCNNUniversality.exists_shared_bias_carrier_layer
#print axioms OneChannelCNNUniversality.horizontalBoundaryTransform_injective
#print axioms OneChannelCNNUniversality.horizontalSharedCarrier_left
#print axioms OneChannelCNNUniversality.horizontalSharedCarrier_interior
#print axioms OneChannelCNNUniversality.exists_horizontal_shared_carrier_layer
#print axioms OneChannelCNNUniversality.sharedLayer_select_target_of_carrier_gap
#print axioms OneChannelCNNUniversality.exists_uniform_feature_margin
#print axioms OneChannelCNNUniversality.exists_sharedBias_select_from_unit_address
