import OneChannelCNNUniversality.SharedBiasParallelStripeNonnegativeInterface

namespace OneChannelCNNUniversality

#check SharedBiasNetwork.outRows_eq_add_depth_two
#check SharedBiasNetwork.outCols_eq_add_depth_two
#check SharedBiasNetworkTo.depth_eq_one_of_oneTwo_to_twoThree
#check SharedBiasNetworkTo.exists_single_layer_representation_oneTwo_to_twoThree
#check exists_parallelStripePackedAffineNetwork_nonnegative_loaded_input_on_compact
#check parallelStripeNonnegativeExampleOffsets
#check parallelStripeLoadedAffineInput_example_south
#check parallelStripeLoadedAffineInput_example_nonnegative
#check not_oneLayer_parallelStripe_nonnegative_example
#check not_exists_exactSize_parallelStripe_nonnegative_initializer

#print axioms SharedBiasNetwork.outRows_eq_add_depth_two
#print axioms SharedBiasNetworkTo.depth_eq_one_of_oneTwo_to_twoThree
#print axioms exists_parallelStripePackedAffineNetwork_nonnegative_loaded_input_on_compact
#print axioms parallelStripeLoadedAffineInput_example_nonnegative
#print axioms not_oneLayer_parallelStripe_nonnegative_example
#print axioms not_exists_exactSize_parallelStripe_nonnegative_initializer

end OneChannelCNNUniversality
